"""The override tracer end to end, against a temporary copy of the fixture
catalog (§6.8, §39.16, ADR 0003, ADR 0004, ADR 0005, ADR 0007).

Runs against a temporary copy, never the committed fixture directly -- same
reason as ``tests/integration/test_generate.py``: this exercises real
``derived/`` and ``overrides/`` folders, and the fixture catalog must never
contain either.

``giant_green_anemone``'s cut file is one piece, already ``pass`` at the
catalog default (``tests/fixtures/catalog/README.md``); these tests build
its override from its own generated bytes plus a harmless trailing XML
comment (never touching its geometry), so the override is guaranteed to
validate identically to the generated file it started from -- the point of
these tests is the override *mechanism* (detection, its own status and
provenance, never overwritten), not a specific cut-file repair.
"""

import json
import shutil
from pathlib import Path

import pytest
from typer.testing import CliRunner

from vectorpress.catalog.findings import findings_path
from vectorpress.catalog.overrides import (
    override_path,
    override_provenance_path,
    read_override_provenance,
)
from vectorpress.catalog.provenance import DERIVED_DIRNAME, read_provenance, sha256_bytes
from vectorpress.catalog.status import read_status
from vectorpress.cli.app import app
from vectorpress.domain.derivative_type import DerivativeType

runner = CliRunner()

FIXTURE_CATALOG_ROOT = Path(__file__).parents[1] / "fixtures" / "catalog"
ASSET_ID = "giant_green_anemone"
FILENAME = "giant-green-anemone-cut.svg"


@pytest.fixture
def temp_catalog_root(tmp_path: Path) -> Path:
    root = tmp_path / "catalog"
    shutil.copytree(FIXTURE_CATALOG_ROOT, root)
    return root


def _derived_dir(root: Path, asset_id: str = ASSET_ID) -> Path:
    return root / "assets" / asset_id / DERIVED_DIRNAME


def _hand_edit(svg_bytes: bytes, comment: bytes = b"<!-- hand-edited -->") -> bytes:
    """A trivial, geometry-preserving edit: append an XML comment just
    before the closing tag. Never touches the traced path data, so an
    override built this way validates identically to the generated file it
    started from."""
    text = svg_bytes.decode("utf-8")
    assert "</svg>" in text
    return text.replace("</svg>", comment.decode("utf-8") + "</svg>").encode("utf-8")


def _write_override(root: Path, data: bytes, asset_id: str = ASSET_ID) -> Path:
    path = override_path(root / "assets" / asset_id, FILENAME)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


# --- acceptance criterion 1: detection, own status, validated as pass --------------


@pytest.mark.integration
def test_an_override_shows_overridden_and_needs_review_and_validates_pass(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    monkeypatch.chdir(temp_catalog_root)
    runner.invoke(app, ["generate", ASSET_ID])
    generated_bytes = (_derived_dir(temp_catalog_root) / FILENAME).read_bytes()
    _write_override(temp_catalog_root, _hand_edit(generated_bytes))

    asset_result = runner.invoke(app, ["asset", ASSET_ID])
    assert asset_result.exit_code == 0, asset_result.output
    cut_svg_line = next(
        line for line in asset_result.stdout.splitlines() if line.strip().startswith("cut_svg")
    )
    assert "override" in cut_svg_line
    assert "needs review" in cut_svg_line

    validate_result = runner.invoke(app, ["validate", ASSET_ID])
    assert validate_result.exit_code == 0, validate_result.output
    assert f"{ASSET_ID}\tcut_svg\t{FILENAME}\tpass" in validate_result.stdout
    assert "(override)" in validate_result.stdout


# --- acceptance criterion 2: approve the override; --force leaves it untouched (§39.16) --


@pytest.mark.integration
def test_approve_approves_the_override_and_force_regenerate_leaves_it_untouched(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    monkeypatch.chdir(temp_catalog_root)
    runner.invoke(app, ["generate", ASSET_ID])
    generated_bytes = (_derived_dir(temp_catalog_root) / FILENAME).read_bytes()
    override_bytes = _hand_edit(generated_bytes)
    override_file = _write_override(temp_catalog_root, override_bytes)
    runner.invoke(app, ["validate", ASSET_ID])  # writes the override's findings report

    approve_result = runner.invoke(app, ["approve", ASSET_ID, "cut_svg"])
    assert approve_result.exit_code == 0, approve_result.output
    assert "approved" in approve_result.stdout

    override_bytes_before = override_file.read_bytes()
    findings_report_path = findings_path(
        _derived_dir(temp_catalog_root), FILENAME, is_override=True
    )
    findings_before = findings_report_path.read_bytes()

    forced = runner.invoke(app, ["generate", "--force", ASSET_ID])
    assert forced.exit_code == 0, forced.output

    # the override's own file, status, and findings are all untouched --
    # the generated file may have been rewritten (idempotently), but never
    # the override's.
    assert override_file.read_bytes() == override_bytes_before
    assert findings_report_path.read_bytes() == findings_before

    asset_result = runner.invoke(app, ["asset", ASSET_ID])
    cut_svg_line = next(
        line for line in asset_result.stdout.splitlines() if line.strip().startswith("cut_svg")
    )
    assert "approved" in cut_svg_line

    # the generated file's own status is untouched by the override's approval.
    generated_status = read_status(_derived_dir(temp_catalog_root), DerivativeType.CUT_SVG)
    assert generated_status is None or generated_status.status.value != "approved"


# --- acceptance criterion 3: editing the override returns it to needs review --------


@pytest.mark.integration
def test_editing_the_override_returns_it_to_needs_review_and_stales_its_findings(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    monkeypatch.chdir(temp_catalog_root)
    runner.invoke(app, ["generate", ASSET_ID])
    generated_bytes = (_derived_dir(temp_catalog_root) / FILENAME).read_bytes()
    override_file = _write_override(temp_catalog_root, _hand_edit(generated_bytes))
    runner.invoke(app, ["validate", ASSET_ID])
    runner.invoke(app, ["approve", ASSET_ID, "cut_svg"])

    approved = runner.invoke(app, ["asset", ASSET_ID])
    approved_line = next(
        line for line in approved.stdout.splitlines() if line.strip().startswith("cut_svg")
    )
    assert "approved" in approved_line

    override_file.write_bytes(_hand_edit(generated_bytes, comment=b"<!-- edited again -->"))

    asset_result = runner.invoke(app, ["asset", ASSET_ID])
    cut_svg_line = next(
        line for line in asset_result.stdout.splitlines() if line.strip().startswith("cut_svg")
    )
    assert "needs review" in cut_svg_line
    assert "approved" not in cut_svg_line
    assert "findings stale" in cut_svg_line


# --- acceptance criterion 4: override provenance; overrides/ is never written -------


@pytest.mark.integration
def test_override_provenance_records_the_source_hash_it_was_edited_against(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    monkeypatch.chdir(temp_catalog_root)
    runner.invoke(app, ["generate", ASSET_ID])
    generated_provenance = read_provenance(_derived_dir(temp_catalog_root), FILENAME)
    assert generated_provenance is not None
    generated_bytes = (_derived_dir(temp_catalog_root) / FILENAME).read_bytes()
    override_bytes = _hand_edit(generated_bytes)
    _write_override(temp_catalog_root, override_bytes)

    approve_result = runner.invoke(app, ["approve", ASSET_ID, "cut_svg"])
    assert approve_result.exit_code == 0, approve_result.output

    override_provenance = read_override_provenance(_derived_dir(temp_catalog_root), FILENAME)
    assert override_provenance is not None
    assert override_provenance.source_hash == generated_provenance.source_hash
    assert override_provenance.output_hash == sha256_bytes(override_bytes)

    provenance_path = override_provenance_path(_derived_dir(temp_catalog_root), FILENAME)
    assert provenance_path.parent == _derived_dir(temp_catalog_root)


@pytest.mark.integration
def test_nothing_is_ever_written_under_overrides(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    monkeypatch.chdir(temp_catalog_root)
    runner.invoke(app, ["generate", ASSET_ID])
    generated_bytes = (_derived_dir(temp_catalog_root) / FILENAME).read_bytes()
    override_bytes = _hand_edit(generated_bytes)
    override_file = _write_override(temp_catalog_root, override_bytes)
    overrides_dir = override_file.parent
    before = {p: p.read_bytes() for p in overrides_dir.iterdir() if p.is_file()}

    runner.invoke(app, ["asset", ASSET_ID])
    runner.invoke(app, ["validate", ASSET_ID])
    runner.invoke(app, ["approve", ASSET_ID, "cut_svg"])
    runner.invoke(app, ["generate", "--force", ASSET_ID])

    after = {p: p.read_bytes() for p in overrides_dir.iterdir() if p.is_file()}
    assert after == before


# --- acceptance criterion 5: an unrecognised override file is reported, not crashed -


@pytest.mark.integration
def test_an_unrecognized_override_file_is_reported_not_an_error(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    monkeypatch.chdir(temp_catalog_root)
    stray_path = temp_catalog_root / "assets" / ASSET_ID / "overrides" / "not-a-real-derivative.svg"
    stray_path.parent.mkdir(parents=True, exist_ok=True)
    stray_path.write_text("<svg></svg>", encoding="utf-8")

    result = runner.invoke(app, ["asset", ASSET_ID])

    assert result.exit_code == 0, result.output
    assert "not-a-real-derivative.svg" in result.stdout
    assert "ignored" in result.stdout


# --- vpress status: the override's status is what is counted (§6.8) ----------------


@pytest.mark.integration
def test_vpress_status_counts_the_overrides_status_not_the_generated_files(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    monkeypatch.chdir(temp_catalog_root)
    runner.invoke(app, ["generate", ASSET_ID])
    runner.invoke(app, ["approve", ASSET_ID, "cut_svg"])  # approves the generated file
    generated_bytes = (_derived_dir(temp_catalog_root) / FILENAME).read_bytes()
    _write_override(temp_catalog_root, _hand_edit(generated_bytes))

    status_result = runner.invoke(app, ["status"])
    assert status_result.exit_code == 0, status_result.output
    # the override is newly seen (needs_review), even though the generated
    # file underneath it was approved.
    status_lines = status_result.stdout.splitlines()
    needs_review_line = next(line for line in status_lines if line.startswith("Needs review:"))
    approved_line = next(line for line in status_lines if line.startswith("Approved:"))
    assert int(needs_review_line.split(":")[1].strip()) >= 1
    assert int(approved_line.split(":")[1].strip()) == 0


# Acceptance criterion 6 (unit-level effective-derivative resolution: override
# present / absent / generated missing) lives in
# tests/unit/test_catalog_overrides.py.


@pytest.mark.integration
def test_generated_files_own_state_json_is_untouched_by_an_overrides_approval(
    monkeypatch: pytest.MonkeyPatch, temp_catalog_root: Path
) -> None:
    """Approving an override writes only the override's own state file --
    the generated file's own ``_state.json`` (locked byte-for-byte by
    ``tests/integration/test_review.py``'s
    ``test_state_json_shape_is_locked_by_snapshot``) never gains an
    override-shaped entry."""
    monkeypatch.chdir(temp_catalog_root)
    runner.invoke(app, ["generate", ASSET_ID])
    generated_state_path = _derived_dir(temp_catalog_root) / "_state.json"
    bytes_before = generated_state_path.read_bytes()
    generated_bytes = (_derived_dir(temp_catalog_root) / FILENAME).read_bytes()
    _write_override(temp_catalog_root, _hand_edit(generated_bytes))

    runner.invoke(app, ["approve", ASSET_ID, "cut_svg"])

    assert generated_state_path.read_bytes() == bytes_before
    override_state_path = _derived_dir(temp_catalog_root) / "_overrides_state.json"
    assert override_state_path.is_file()
    data = json.loads(override_state_path.read_text(encoding="utf-8"))
    assert data["cut_svg"]["status"] == "approved"
