"""catalog.status: tool-owned per-derivative status persisted in one
asset's derived/_state.json (ADR 0004, ADR 0005, §10, §22.1).
"""

import json
from pathlib import Path

from vectorpress.catalog.provenance import sha256_bytes
from vectorpress.catalog.status import (
    STATE_FILENAME,
    asset_derivative_status,
    read_all_statuses,
    read_status,
    state_path,
    write_status,
)
from vectorpress.domain.derivative_type import DerivativeType
from vectorpress.domain.status import Status, StatusRecord

HASH_A = "a" * 64
HASH_B = "b" * 64


# --- read/write round trip ---------------------------------------------------------


def test_write_then_read_round_trips_the_status_record(tmp_path: Path) -> None:
    record = StatusRecord(status=Status.NEEDS_REVIEW, note=None, output_hash=HASH_A)

    write_status(tmp_path, DerivativeType.CUT_SVG, record)

    assert read_status(tmp_path, DerivativeType.CUT_SVG) == record


def test_read_status_returns_none_when_no_record_exists(tmp_path: Path) -> None:
    assert read_status(tmp_path, DerivativeType.CUT_SVG) is None


def test_status_lives_beside_the_derivative_never_inside_it(tmp_path: Path) -> None:
    record = StatusRecord(status=Status.APPROVED, note="clean", output_hash=HASH_A)

    write_status(tmp_path, DerivativeType.CUT_SVG, record)

    path = state_path(tmp_path)
    assert path.name == STATE_FILENAME
    data = json.loads(path.read_text(encoding="utf-8"))
    assert data["cut_svg"]["status"] == "approved"
    assert data["cut_svg"]["note"] == "clean"
    assert data["cut_svg"]["output_hash"] == HASH_A


def test_every_derivative_types_status_lives_in_the_same_state_file(tmp_path: Path) -> None:
    """Unlike provenance and findings (one JSON file per derivative file),
    every derivative type's status for one asset lives together in a single
    _state.json (ADR 0005's per-asset layout)."""
    write_status(
        tmp_path,
        DerivativeType.CUT_SVG,
        StatusRecord(status=Status.APPROVED, note=None, output_hash=HASH_A),
    )
    write_status(
        tmp_path,
        DerivativeType.TRANSPARENT_PNG,
        StatusRecord(status=Status.NEEDS_REVIEW, note=None, output_hash=HASH_B),
    )

    statuses = read_all_statuses(tmp_path)

    assert statuses[DerivativeType.CUT_SVG].status is Status.APPROVED
    assert statuses[DerivativeType.TRANSPARENT_PNG].status is Status.NEEDS_REVIEW
    assert len([p for p in tmp_path.iterdir() if p.name.endswith(".json")]) == 1


# --- atomic, idempotent writes -------------------------------------------------------


def test_write_status_does_not_rewrite_when_the_record_already_matches(tmp_path: Path) -> None:
    record = StatusRecord(status=Status.APPROVED, note="clean", output_hash=HASH_A)
    write_status(tmp_path, DerivativeType.CUT_SVG, record)
    path = state_path(tmp_path)
    mtime_before = path.stat().st_mtime_ns
    bytes_before = path.read_bytes()

    write_status(tmp_path, DerivativeType.CUT_SVG, record)

    assert path.stat().st_mtime_ns == mtime_before
    assert path.read_bytes() == bytes_before


def test_write_status_rewrites_when_the_record_differs(tmp_path: Path) -> None:
    write_status(
        tmp_path,
        DerivativeType.CUT_SVG,
        StatusRecord(status=Status.NEEDS_REVIEW, note=None, output_hash=HASH_A),
    )

    write_status(
        tmp_path,
        DerivativeType.CUT_SVG,
        StatusRecord(status=Status.APPROVED, note="clean", output_hash=HASH_A),
    )

    assert read_status(tmp_path, DerivativeType.CUT_SVG) == StatusRecord(
        status=Status.APPROVED, note="clean", output_hash=HASH_A
    )


def test_write_status_creates_the_derived_directory(tmp_path: Path) -> None:
    derived_dir = tmp_path / "derived"
    record = StatusRecord(status=Status.NEEDS_REVIEW, note=None, output_hash=HASH_A)

    write_status(derived_dir, DerivativeType.CUT_SVG, record)

    assert state_path(derived_dir).is_file()


def test_write_status_leaves_no_temp_file_behind(tmp_path: Path) -> None:
    record = StatusRecord(status=Status.NEEDS_REVIEW, note=None, output_hash=HASH_A)

    write_status(tmp_path, DerivativeType.CUT_SVG, record)

    leftover = [p for p in tmp_path.iterdir() if p.name.endswith(".tmp")]
    assert leftover == []


# --- asset_derivative_status: legacy and "status follows the bytes" ----------------


def test_asset_derivative_status_is_needs_review_for_a_legacy_derivative_with_no_record(
    tmp_path: Path,
) -> None:
    output_bytes = b"generated bytes"

    record = asset_derivative_status(tmp_path, DerivativeType.CUT_SVG, output_bytes)

    assert record.status is Status.NEEDS_REVIEW
    assert record.note is None


def test_asset_derivative_status_returns_the_stored_record_when_bytes_match(
    tmp_path: Path,
) -> None:
    output_bytes = b"generated bytes"

    write_status(
        tmp_path,
        DerivativeType.CUT_SVG,
        StatusRecord(status=Status.APPROVED, note="clean", output_hash=sha256_bytes(output_bytes)),
    )

    record = asset_derivative_status(tmp_path, DerivativeType.CUT_SVG, output_bytes)

    assert record.status is Status.APPROVED
    assert record.note == "clean"


def test_asset_derivative_status_is_needs_review_when_disk_bytes_no_longer_match(
    tmp_path: Path,
) -> None:
    """Editing a derivative's bytes on disk after approval makes it report
    needs_review -- ADR 0004's "status follows the bytes"."""
    write_status(
        tmp_path,
        DerivativeType.CUT_SVG,
        StatusRecord(status=Status.APPROVED, note="clean", output_hash=HASH_A),
    )

    record = asset_derivative_status(tmp_path, DerivativeType.CUT_SVG, b"hand-edited bytes")

    assert record.status is Status.NEEDS_REVIEW
    assert record.note is None
